platform:ios,'7.0'
target 'TMX3DPrinter' do
pod 'MJExtension','~>3.0.10'
pod 'MJRefresh','~>3.1.0'
pod 'AFNetworking','~>3.0.4'
pod 'MBProgressHUD','~>0.9.2'
pod 'SDWebImage','~>3.7.5'
pod 'Masonry','~>0.6.4'
pod 'IQKeyboardManager','~>3.3.6'
pod 'MMDrawerController','~>0.6.0'
end
